In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("seq.csv")
df.head()

                                            sequence
0  ACWDNBFLKFNVNFSNSNVNFVNDFLKNSLCVNDKVNFNVRJDNSN...
1  SKNVJJNVGFBNBNNVFKVDNVKLGNBFGLKTLREFMVKLDFMVDK...
2  SDVDVFNDFKLNDFKLVNS'KVNDKJVNJKBNTGNGRTIJGIORJF...
3  DIFJVDFNJVKFNBFGJNBSXJFIJAIDFIVGFJBNSDJVNFJVBF...
4  JNFVJKDNV JKDN VKJDN KJDFNVJDFVNNVJDFVBNHUIHEI...

In [ ]:
import random

In [ ]:
df["mixed sequence"]= df["sequence"].apply(lambda row: random.sample(row, k=10))
df.head()

,sequence,mixed sequence
0,ACWDNBFLKFNVNFSNSNVNFVNDFLKNSLCVNDKVNFNVRJDNSN...,"[N, F, M, V, S, D, N, N, K, N]"
1,SKNVJJNVGFBNBNNVFKVDNVKLGNBFGLKTLREFMVKLDFMVDK...,"[N, N, S, M, K, G, V, R, B, K]"
2,SDVDVFNDFKLNDFKLVNS'KVNDKJVNJKBNTGNGRTIJGIORJF...,"[K, N, N, G, S, N, S, V, V, D]"
3,DIFJVDFNJVKFNBFGJNBSXJFIJAIDFIVGFJBNSDJVNFJVBF...,"[N, V, F, V, X, N, D, J, B, V]"
4,JNFVJKDNV JKDN VKJDN KJDFNVJDFVNNVJDFVBNHUIHEI...,"[D, I, N, E, F, E, U, J, K, B]"

In [ ]:
df["combined"]= df["mixed sequence"].apply(lambda row:"".join(row))

In [ ]:
df.head()

,sequence,mixed sequence,combined
0,ACWDNBFLKFNVNFSNSNVNFVNDFLKNSLCVNDKVNFNVRJDNSN...,"[N, F, M, V, S, D, N, N, K, N]",NFMVSDNNKN
1,SKNVJJNVGFBNBNNVFKVDNVKLGNBFGLKTLREFMVKLDFMVDK...,"[N, N, S, M, K, G, V, R, B, K]",NNSMKGVRBK
2,SDVDVFNDFKLNDFKLVNS'KVNDKJVNJKBNTGNGRTIJGIORJF...,"[K, N, N, G, S, N, S, V, V, D]",KNNGSNSVVD
3,DIFJVDFNJVKFNBFGJNBSXJFIJAIDFIVGFJBNSDJVNFJVBF...,"[N, V, F, V, X, N, D, J, B, V]",NVFVXNDJBV
4,JNFVJKDNV JKDN VKJDN KJDFNVJDFVNNVJDFVBNHUIHEI...,"[D, I, N, E, F, E, U, J, K, B]",DINEFEUJKB

In [ ]:
df.to_excel(r"C:\Users\Admin\Desktop\Биоинформатика\Научка\mixed sequences.xlsx", index= False)